---
- name: lab
  ram: 2048
  cpus: 2
  ip: '192.168.56.101'
  script: "script"
  images:
    - "alpine:3.16.2"
    - "ubuntu:20.04"
    - "nginx:1.23.1"
    - "registry:2"
- name: client
  ram: 1024
  cpus: 1
  ip: '192.168.56.102'
  script: "daemon"
  images: []
