---
- name: lab
  ram: 2048
  cpus: 2
  ip: '192.168.56.101'
  images:
    - "alpine:3.16.2"
    - "ubuntu:20.04"
    - "nginx:alpine"
    - "registry:2"
    - "redis:alpine"
    - "python:3.7-alpine"
    - "squidfunk/mkdocs-material:8.5.3"
    - "ikauzak/docker-course-docs:latest"
- name: client
  ram: 1024
  cpus: 1
  ip: '192.168.56.102'
  images: []
