---
- name: lab
  ram: 1024
  cpus: 1
  ip: '192.168.56.101'
  images:
    - "alpine:3.16.2"
    - "ubuntu:20.04"
    - "nginx:alpine"
    - "registry:2"
    - "redis:alpine"
    - "python:3.7-alpine"
    - "mcr.microsoft.com/dotnet/sdk:6.0"
    - "ikauzak/docker-course-docs:latest"
